### ISSUE TITLE
Check for some gpio pins

### ISSUE THREAD

**Issue by renegadeandy** [SensorsIot/ESP32-Board-Test#1]
Hello to the man with the Swiss accent,

I am using this esp32 board : https://www.amazon.co.uk/gp/product/B072JVQVND/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

The list of pins you have tested in the GPIO discovery program is as follows:

`int gpio[100] = {0, 4, 5, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 32, 33, 99};`

Note that you do not test pin 99.

There are several pins on my board which seems to match your yellow dev board that you tend to use. The silkscreen names for these pins are as follows:

1. TXD - BOTTOM ROW
2. RXD - BOTTOM ROW
3. G2 - BOTTOM ROW
4. G15 - BOTTOM ROW
5. SD1 - BOTTOM ROW
6. SD0 - BOTTOM ROW
7. CLK - BOTTOM ROW
8. V5 - TOP ROW (ASSUME THIS IS 5V OUT)
9. CMD - TOP ROW
10. SD3 - TOP ROW
11. SD2 - TOP ROW
12. GND  - TOP ROW (ASSUME THIS IS GROUND)
13. G35 - TOP ROW
14. G34 - TOP ROW
15. G34 - TOP ROW
16. SW - TOP ROW
17. SP - TOP ROW
18. EN - TOP ROW (ASSUME THIS IS ENABLE / RESET PIN)
19. 3V3 - TOP ROW (ASSUME THIS IS 3.3V OUTPUT)

For these 19 pins, some of them seem like they could potentially be GPIO , Why are they not tested in the GPIO discovery program?

**Comment by SensorsIot** [comment]
The # 99 is to tell the program to stop. And teh pins are different for every board.
