### ISSUE TITLE
Dual antenna module ESP32WROOM-DA scans less APs in auto antenna mode

### ISSUE THREAD

**Issue by jack0c** [SensorsIot/ESP32-Board-Test#2]
I am not sure where to put the issue is the best way.
I am a maintainer for esp-idf, just saw you report the bug here:https://www.youtube.com/watch?v=F0u5qIwwY1k
Can you help to fill more information in the GitHub issue so that we can follow the issue, and get it back to you later.
https://github.com/espressif/esp-idf/issues/8824

**Comment by SensorsIot** [comment]
Hi,
SpriteTM wrote that he already created an internal message for the problem in your company. So I do not know the status. I do not have more information than shown in the video. But as you see, I use the Arduino IDE.
We were also not sure if it is a documentation issue or a real bug (there is no documentation available)

**Comment by jack0c** [comment]
Sure, if we can reproduce your phenomenon, we do not need more information, else we will ask for more information.
Add the issue is just make sure there is a channel we can give the feed back to you though which will be not fast enough because of the lock down in Shanghai. If you will follow  the GitHub issue https://github.com/espressif/esp-idf/issues/8824, then you can just close this issue.

**Comment by SensorsIot** [comment]
I wrote a comment into issue https://github.com/espressif/esp-idf/issues/8824  . Now I should get the updates. Thanks!
